project finished
TheCSharpAcademy/CodeReviews.Console.ExerciseTracker pull request #35
Opened 2024-05-06 00:07 UTC by Jinboi

Project finished

As always, thank you for your guidance!

2024-05-19 07:24 UTC, stevietv requested changes
Hi @Jinboi 
Currently your program crashes. Please fix this and check that it runs , then push up the fix.
Cheers!

2024-05-19 07:24 UTC, stevietv commented on ExerciseTracker.Bata13/STUDY.ConsoleProjects.ExerciseTrackerFour/Data/ExerciseDbContext.cs
> +            .AddJsonFile("appsettings.config")
your code is looking for an `appsettings.config` json file, which doesn't exist.

2024-05-19 22:51 UTC, Jinboi commented on ExerciseTracker.Bata13/STUDY.ConsoleProjects.ExerciseTrackerFour/Data/ExerciseDbContext.cs
> +            .AddJsonFile("appsettings.config")
I've fixed the bug and re-submitted.
Thank you!

2024-05-20 10:42 UTC, stevietv commented
Hi @Jinboi 
thanks for the update. I've ran your program and encountered a few issues:

* The program crashes when I enter an invalid date. It seems you are only using TryParseExact in the update method but not the add method.
* you have not used Dependency Injection, which is a requirement of the project

Can you take a look at working on meeting the requirement for dependency injection

2024-05-20 23:52 UTC, Jinboi commented
Hi Stevietvm

I've re-submitted after fixing DI request and invalid bug. Please let me know if there's anything wrong! Thank you!

2024-05-30 21:11 UTC, TheCSharpAcademy commented
@stevietv Any updates on this one? 🤓

2024-05-31 06:48 UTC, stevietv commented
@TheCSharpAcademy  - see my discord message asking for your input

2024-06-03 16:16 UTC, stevietv commented
I discussed with Pablo and he was happy with the usage of DI so good work! ✅

2024-06-03 16:16 UTC, stevietv approved these changes

2024-06-03 16:16 UTC, merged