Added the basic structure of the Project files
TheCSharpAcademy/CodeReviews.Console.ExerciseTracker pull request #39
Opened 2024-06-22 08:58 UTC by javedkhan2k2

2024-07-05 15:45 UTC, Doc415 requested changes
Waiting for your updates :) Good luck.

2024-07-05 15:45 UTC, Doc415 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/appsettings.json
Hey there is no connection string in appsettings file 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.ExerciseTracker/assets/94632226/a25f7266-0a4f-4b84-91d3-559dc659d40f)

So the application throws exception at the beggining. If you can add the default conntection string part, we can edit it for our own connection string

2024-07-05 15:45 UTC, Doc415 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/UserInput.cs
> +            if (ValidatorHelper.IsValidDateTimeInputs(exercise.ToExercise()))
when adding exercise, if end date is smaller than start date, validation works , still it would be nice to see a prompt for user telling whats going wrong
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.ExerciseTracker/assets/94632226/15804b35-b29d-4872-b3d1-c71d6d49021d)

2024-07-05 15:45 UTC, Doc415 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/Repositores/JoggingRepository.cs
> +    public async Task<List<Excercise>?> GetAllExercise() => await _context.Excercises.ToListAsync();
if i try to see all jogging exercises before i add any, the application throws exception
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.ExerciseTracker/assets/94632226/a4efc685-ec0e-485d-8e9b-6222a546065e)

2024-07-05 15:45 UTC, Doc415 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/Repositores/JoggingRepository.cs
> +    public async Task<Excercise> AddExercise(Excercise exercise)
When i try do add, update and delete a jogging exercise, the console shows the sql query as info 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.ExerciseTracker/assets/94632226/b7f011fa-d963-4617-9417-a3146237ddbd)

2024-07-06 07:35 UTC, javedkhan2k2 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/appsettings.json
@Doc415 thanks for the awesome review.
I am using Microsoft Secret Manager to store my connection string. Codacy is checking for the secrets therefore I am not saving them in plain text.
Please enter the command in terminal inside Project Directory below to specify the connection string:
`dotnet user-secrets set ConnectionStrings:DefaultConnection "Server=localhost;Database=Exercisetracker;UserId=YourUserID;Password=YourPassword;TrustServerCertificate=True;"`
I will add some validations to check the connection string and add appropriate instructions to resolve the issue.
I will resolve the other issues/bugs and commit.

2024-07-06 07:47 UTC, javedkhan2k2 commented on Exercisetracker.javedkhan2k2/Exercisetracker.javedkhan2k2/Repositores/JoggingRepository.cs
> +    public async Task<Excercise> AddExercise(Excercise exercise)
Previously I received these message as well. Then i changed the Warning level of EF and they didn't appear again.
It is still not coming for me. It is maybe a bug in EF or something.
<img width="609" alt="Screenshot 2024-07-06 at 09 45 47" src="https://github.com/TheCSharpAcademy/CodeReviews.Console.ExerciseTracker/assets/48986371/5cbb4662-00f1-4ea6-a596-99d653501916">

2024-07-06 08:15 UTC, javedkhan2k2 commented
I updated the Code. 
Please check it.

2024-07-08 09:05 UTC, Doc415 approved these changes
Good work :)

2024-07-08 12:11 UTC, closed without merging