Add Gautatyr project
TheCSharpAcademy/CodeReviews.Console.ExerciseTracker pull request #4
Opened 2023-04-14 12:18 UTC by Gautatyr

2023-04-24 05:26 UTC, TheCSharpAcademy requested changes

2023-04-24 05:26 UTC, TheCSharpAcademy commented on Gautatyr.ExerciseTracker/ExerciseTracker/Repositories/RunRepository.cs
> +        return GetAll().FirstOrDefaultAsync(x => x.Id == id);
Even though this isn't a requirement, I'll request this change because this is a very expensive call. You're calling the entire database to get one record. Could you please optimize this so you query only the necessary data?

2023-04-24 05:26 UTC, TheCSharpAcademy commented on Gautatyr.ExerciseTracker/ExerciseTracker/Services/RunService.cs
> +    {
Since this is a fairly simple application I think a service layer isn't necessary. The controller could call the repository directly. A service becomes necessary when the data needs to be processed and you don't want to do it neither in the controller nor in the repository, which should remain pure.

2023-04-24 07:49 UTC, Gautatyr commented on Gautatyr.ExerciseTracker/ExerciseTracker/Services/RunService.cs
> +    {
Ah thank you for saying this haha. I followed the guide on repository pattern and having the service layer on top of the repository even though they basically do the same calls was so weird to me.

2023-04-27 00:15 UTC, TheCSharpAcademy commented on Gautatyr.ExerciseTracker/ExerciseTracker/Services/RunService.cs
> +    {
@Gautatyr I think they do it this way because in most cases the data will some sort of processing, hence a service is needed. But here we're literally repeating the calls. 😊

2023-04-27 00:21 UTC, TheCSharpAcademy requested changes
I found another bug. The end date can't be before the start date. 😔

Also, looks like the get By Id method wasn't implemented? 

![image](https://user-images.githubusercontent.com/108711476/234729257-97a6e292-84df-4c23-a81e-a3335ac758a1.png)

2023-04-27 05:59 UTC, Gautatyr commented
I think the GetById method got broken when I deleted the service layer, it is working now.
Also you're right the end date shouldn't be before the start haha, it is fixed too.

Thanks for the review !

2023-05-08 20:22 UTC, merged