Create: an exercise tracker app
TheCSharpAcademy/CodeReviews.Console.ExerciseTracker pull request #58
Opened 2024-11-21 19:07 UTC by MefDev

This is an application record exercise data.
1- Usage of Entity Framework for data-persistence.
2- usage of dependency injection to access the repository from the controller.

2024-11-27 14:05 UTC, chrisjamiecarter requested changes
Hey @MefDev 👋,

Well done on your Exercise Tracker project submission 🎉 !

I have performed a peer review and have added bespoke comments with praise and suggestions. Also, see below for some general feedback.

***

🟠 **Spectre Console**
Why don't you use this UI library for ID selections? Display the list of exercises, the key tied to the ID. That way user can only select a valid option and also doesn't have to manually enter an ID.
Don't forget to give a cancel option.

🟠 **Seed Data**
Why don't you seed the database with some initial data? Will make testing easier.

***

Please revisit to try understand and fix the 🔴 issues 🔧 , as these relate to the project requirements and they block my approval.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

2024-11-27 14:05 UTC, chrisjamiecarter commented on ExerciseTracker.Mefdev/Controllers/ExerciseController.cs
> +    public void DeleteExercise()
🔴 **Not Working**

💡 Looks like delete doesn't work
![image](https://github.com/user-attachments/assets/5103335b-357f-4249-b0dd-2ee31268a3b3)

2024-11-28 21:29 UTC, MefDev commented on ExerciseTracker.Mefdev/UserInputs/UserInput.cs
> +        .Validate(name =>
I've  supposed that comments should be greater than 5 characters. However, I don't think that the case. Now, I check only for empty inputs.

2024-11-28 21:32 UTC, MefDev commented on ExerciseTracker.Mefdev/Controllers/ExerciseController.cs
> +        DateTime endDate = _userInput.GetDate();
I'm handling that when inside **GetDuration()** method.

2024-11-28 21:35 UTC, MefDev commented on ExerciseTracker.Mefdev/Context/ExerciseContext.cs
> +        => options.UseSqlServer(Environment.GetEnvironmentVariable("CONNECTION_STRING"));
I was just experimenting with using environment variables since they're easy to use. However I will change to that appsetting.json file in my next push.

2024-11-29 12:24 UTC, chrisjamiecarter commented on ExerciseTracker.Mefdev/Context/ExerciseContext.cs
> +        => options.UseSqlServer(Environment.GetEnvironmentVariable("CONNECTION_STRING"));
No it isn't a problem, I was just interested in your justification.

2024-11-29 20:38 UTC, MefDev commented
Now, when you run the app a random data would be seed into the Db. In addition, I make use of Ansi console selection of functionality instead of pushing the user to write a raw Id.

2024-11-30 17:42 UTC, chrisjamiecarter approved these changes
Hey @MefDev 👋 ,

Well done on getting the updates pushed through!

***

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

2024-11-30 18:46 UTC, closed without merging